auth_condominio/urls.py
from django.urls import path

from . import views

app_name = 'auth_condominio'

urlpatterns = [
    path('login/', views.loginView, name = 'login'),
    path('logout/', views.logoutView, name = 'logout'),
    path('register/', views.registerView, name = 'register'),

]

condominio/urls.py
from django.urls import path

from . import views

app_name = 'condominio'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('Visitantes', views.lista_visitante, name = 'lista_visitante'),
    path('Crear_Visitante', views.crear_visitante, name = 'crear_visitante'),
    path('Editar_Visitante/<int:visitante_id>', views.editar_visitante, name = 'editar_visitante'),
    path('Eliminar_Visitante/<int:visitante_id>', views.eliminar_visitante, name = 'eliminar_visitante'),
    path('Visitas', views.lista_visita, name = 'lista_visita'),
    path('Crear_Visita', views.crear_visita, name = 'crear_visita'),
    path('Editar_Visita/<int:visita_id>', views.editar_visita, name = 'editar_visita'),
    path('Eliminar_Visita/<int:visita_id>', views.eliminar_visita, name = 'eliminar_visita'),
    path('Departamentos', views.lista_departamento, name = 'lista_departamento'),
    path('Crear_Departamento', views.crear_departamento, name = 'crear_departamento'),
    path('Editar_Departamento/<int:departamento_id>', views.editar_departamento, name = 'editar_departamento'),
    path('Eliminar_Departamento/<int:departamento_id>', views.eliminar_departamento, name = 'eliminar_departamento'),

    path('Anuncios/', views.verAnunciosViews, name = 'anuncios'),
    path('Anuncios/crear/', views.crearAnunciosViews, name = 'crearAnun'),
    path('Anuncios/borrar/<int:anuncio_id>', views.borrarAnuncioViews, name = 'borrarAnun'),
    path('Anuncios/editar/<int:anuncio_id>', views.editarAnuncioViews, name = 'editarAnun'),

    path('Usuarios/perfiles/', views.verUsuariosViews, name = 'usuarios'),
    path('Usuarios/perfiles/editar/<int:perfil_id>', views.editarUsuariosViews, name = 'editarUser'),
    path('Usuarios/perfiles/borrar/<int:usuario_id>', views.borrarUsuarioViews, name = 'borrarUser'),

    path('Perfil/', views.verPerfilViews, name = 'perfil'),
    path('Perfil/Changepassword/', views.actualizarPassPerfil, name = 'perfilPass'),

]

main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('condominio.urls')),
    path('auth/', include('auth_condominio.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

condominio/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Perfil(models.Model):
    rut = models.CharField('Rut', max_length=20, null=False, blank=False)
    foto_perfil = models.ImageField('Foto de perfil',
        upload_to='fotos/perfil',
        blank=True,
        null=True
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        ordering = ['id']
        verbose_name = 'Perfil'
        verbose_name_plural = 'Perfiles'

    def __str__(self):
        return str(self.user)


class Anuncio(models.Model):
    titulo = models.CharField('Titulo', max_length=100, null=False, blank=False)
    descripcion = models.TextField('Descripción', max_length=500, null=False, blank=False)
    fecha = models.DateTimeField(auto_now_add=True)
    foto_anuncio = models.ImageField('Foto del anuncio',
        upload_to='fotos/anuncio',
        blank=True,
        null=True
    )

    perfil = models.ForeignKey(Perfil, on_delete=models.CASCADE, null=False, blank=False)

    class Meta:
        ordering = ['titulo']
        verbose_name = 'Anuncio'
        verbose_name_plural = 'Anuncios'

    def __str__(self):
        return self.titulo


class Departamento(models.Model):
    numero = models.CharField('N° Departamento', max_length=15, null=False, blank=False)

    perfil = models.ManyToManyField(Perfil, blank=True, related_name='depto_perfil')

    class Meta:
        ordering = ['numero']
        verbose_name = 'Departamento'
        verbose_name_plural = 'Departamentos'

    def __str__(self):
        return self.numero


class Visitante(models.Model):
    nombre = models.CharField('Nombre', max_length=50, null=False, blank=False)
    apellido = models.CharField('Apellido', max_length=50, null=True, blank=True)
    rut = models.CharField('Rut', max_length=20, null=True, blank=True)

    class Meta:
        ordering = ['apellido']
        verbose_name = 'Visitante'
        verbose_name_plural = 'Visitantes'

    def __str__(self):
        return self.nombre


class Visita(models.Model):
    observacion = models.TextField(max_length=500, null=True, blank=True)
    fecha = models.DateTimeField(auto_now_add=True)

    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE, null=False, blank=False)
    visitante = models.ManyToManyField(Visitante, related_name='visitante')

    class Meta:
        ordering = ['id']
        verbose_name = 'Visita'
        verbose_name_plural = 'Visitas'

    def __str__(self):
        return self.departamento.numero
        # return str(self.departamento.numero)

condominio/forms.py
from django import forms
from condominio.models import Perfil, Anuncio, Departamento, Visitante, Visita
from django.contrib.auth.models import User

class VisitanteForm(forms.ModelForm):
    class Meta:
        model = Visitante
        fields = '__all__'

class VisitaForm(forms.ModelForm):
    class Meta:
        model = Visita
        fields = '__all__'

class DepartamentoForm(forms.ModelForm):
    class Meta:
        model = Departamento
        fields = '__all__'

class AnuncioForm(forms.ModelForm):
    class Meta:
        model = Anuncio
        fields = ['titulo',
            'descripcion',
            'foto_anuncio',
        ]

class PerfilForm(forms.ModelForm):
    class Meta:
        model = Perfil
        fields = '__all__'

class UserUpdateForm(forms.ModelForm):
    # email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username',
            'email',
            'first_name',
            'last_name',
        ]

class PerfilUpdateForm(forms.ModelForm):
    class Meta:
        model = Perfil
        fields = ['rut']

condominio/views.py
from django.shortcuts import render, redirect
from condominio.models import Perfil, Anuncio, Departamento, Visitante, Visita
from django.contrib.auth.models import User #, Group
from django.contrib.auth.decorators import login_required, permission_required #, user_passes_test
from condominio.forms import (VisitanteForm,
        VisitaForm,
        DepartamentoForm,
        AnuncioForm,
        PerfilForm,
        UserUpdateForm,
        PerfilUpdateForm
    )

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.core.exceptions import ObjectDoesNotExist

from django.contrib import messages

from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash



def home(request):
    template_name = 'condominio/home.html'
    data = {}

    data['query'] = ''

    return render(request, template_name, data)


##############################################################
##########################VISITANTE###########################
##############################################################
@permission_required('condominio.view_visitante')
def lista_visitante(request):
	template_name = 'condominio/visitante.html'
	data = {}

	data['visitantes'] = Visitante.objects.all()

	return render(request, template_name, data)

@permission_required('condominio.add_visitante')
def crear_visitante(request):
	data = {}
	template_name = 'condominio/crear_visitante.html'

	if request.method == 'POST':
		data['form'] = VisitanteForm(request.POST,files=request.FILES)
		if data['form'].is_valid():
			data['form'].save()
			return redirect('condominio:lista_visitante')
	else:
		data['form'] = VisitanteForm()

	return render(request, template_name, data)

@permission_required('condominio.change_visitante')
def editar_visitante(request, visitante_id):
	data = {}
	template_name = 'condominio/editar_visitante.html'
	visitante = Visitante.objects.get(pk=visitante_id)

	if request.method == 'POST':
		data['form'] = VisitanteForm(request.POST,request.FILES or None, instance=visitante)
		if data['form'].is_valid():
			data['form'].save()
			return redirect('condominio:lista_visitante')
	else:
		data['form'] = VisitanteForm(instance=visitante)

	return render(request, template_name, data)

@permission_required('condominio.delete_visitante')
def eliminar_visitante(request, visitante_id):
	data = {}
	template_name = 'condominio/eliminar_visitante.html'
	data['visitante'] = Visitante.objects.get(pk=visitante_id)

	if request.method == 'POST':
		data['visitante'].delete()
		return redirect('condominio:lista_visitante')

	return render(request, template_name, data)



##############################################################
############################VISITA############################
##############################################################
@permission_required('condominio.view_visita')
def lista_visita(request): #talvez agregar paginador despues de ver que tenemos todo lo necesario en la vista
	template_name = 'condominio/visita.html'
	data = {}

	data['visitas'] = Visita.objects.all()

	return render(request, template_name, data)

@permission_required('condominio.add_visita')
def crear_visita(request):
	data = {}
	template_name = 'condominio/crear_visita.html'

	if request.method == 'POST':
		data['form'] = VisitaForm(request.POST)
		if data['form'].is_valid():
			data['form'].save()
			return redirect('condominio:lista_visita')
	else:
		data['form'] = VisitaForm()

	return render(request, template_name, data)

@permission_required('condominio.change_visita')
def editar_visita(request, visita_id):
	data = {}
	template_name = 'condominio/editar_visita.html'
	visita = Visita.objects.get(pk=visita_id)

	if request.method == 'POST':
		data['form'] = VisitaForm(request.POST,request.FILES or None, instance=visita)
		if data['form'].is_valid():
			data['form'].save()
			return redirect('condominio:lista_visita')
	else:
		data['form'] = VisitaForm(instance=visita)

	return render(request, template_name, data)

@permission_required('condominio.delete_visita')
def eliminar_visita(request, visita_id):
	data = {}
	template_name = 'condominio/eliminar_visita.html'
	data['visita'] = Visita.objects.get(pk=visita_id)

	if request.method == 'POST':
		data['visita'].delete()
		return redirect('condominio:lista_visita')

	return render(request, template_name, data)



##############################################################
##########################DEPARTAMENTO########################
##############################################################
@permission_required('condominio.view_departamento')
def lista_departamento(request):
	template_name = 'condominio/departamento.html'
	data = {}

	data['departamentos'] = Departamento.objects.all()

	return render(request, template_name, data)

@permission_required('condominio.add_departamento')
def crear_departamento(request):
	data = {}
	template_name = 'condominio/crear_departamento.html'

	if request.method == 'POST':
		data['form'] = DepartamentoForm(request.POST,files=request.FILES)
		if data['form'].is_valid():
			data['form'].save()
			return redirect('condominio:lista_departamento')
	else:
		data['form'] = DepartamentoForm()

	return render(request, template_name, data)

@permission_required('condominio.change_departamento')
def editar_departamento(request, departamento_id):
	data = {}
	template_name = 'condominio/editar_departamento.html'
	departamento = Departamento.objects.get(pk=departamento_id)

	if request.method == 'POST':
		data['form'] = DepartamentoForm(request.POST,request.FILES or None, instance=departamento)
		if data['form'].is_valid():
			data['form'].save()
			return redirect('condominio:lista_departamento')
	else:
		data['form'] = DepartamentoForm(instance=departamento)

	return render(request, template_name, data)

@permission_required('condominio.delete_departamento')
def eliminar_departamento(request, departamento_id):
	data = {}
	template_name = 'condominio/eliminar_departamento.html'
	data['departamento'] = Departamento.objects.get(pk=departamento_id)

	if request.method == 'POST':
		data['departamento'].delete()
		return redirect('condominio:lista_departamento')

	return render(request, template_name, data)


##############################################################
###########################ANUNCIOS###########################
##############################################################
@permission_required('condominio.view_anuncio')
def verAnunciosViews(request):
    template_name = 'condominio/anuncios.html'
    data = {}

    # anuncios_list = Anuncio.objects.all().order_by('fecha').reverse()

    #########ANUNCIOS DE LOS ADMIN###############
    page = request.GET.get('page', 1)
    anuncios_list = Anuncio.objects.filter(perfil__user__groups__name__in = ['administrador']).order_by('fecha').reverse()

    paginator = Paginator(anuncios_list, 2)

    try:
        data['anunciosAdmin'] = paginator.page(page)
    except PageNotAnInteger:
        data['anunciosAdmin'] = paginator.page(1)
    except EmptyPage:
        data['anunciosAdmin'] = paginator.page(paginator.num_pages)


    #########ANUNCIOS DE LOS CONSERJES###############
    page2 = request.GET.get('page2', 1)
    anuncios_list2 = Anuncio.objects.filter(perfil__user__groups__name__in = ['conserje']).order_by('fecha').reverse()

    paginator2 = Paginator(anuncios_list2, 2)

    try:
        data['anunciosConserje'] = paginator2.page(page2)
    except PageNotAnInteger:
        data['anunciosConserje'] = paginator2.page(1)
    except EmptyPage:
        data['anunciosConserje'] = paginator2.page(paginator2.num_pages)


    #########ANUNCIOS DE LOS USUARIOS###############
    page3 = request.GET.get('page3', 1)
    anuncios_list3 = Anuncio.objects.filter(perfil__user__groups__name__in = ['habitante']).order_by('fecha').reverse()

    paginator3 = Paginator(anuncios_list3, 5)

    try:
        data['anunciosUser'] = paginator3.page(page3)
    except PageNotAnInteger:
        data['anunciosUser'] = paginator3.page(1)
    except EmptyPage:
        data['anunciosUser'] = paginator3.page(paginator3.num_pages)

    return render(request, template_name, data)

@permission_required('condominio.add_anuncio')
def crearAnunciosViews(request):
    template_name = 'condominio/crear_anuncio.html'
    data = {}

    data['form'] = AnuncioForm(request.POST or None, request.FILES or None)
    try:

        if data['form'].is_valid():
            user_profile = Perfil.objects.get(user=request.user)
            if user_profile:
                instance = data['form'].save(commit=False)
                instance.perfil = user_profile
                instance.save()
                return redirect('condominio:anuncios')
        else:

            data['form'] = AnuncioForm(instance=request.user)
    except ObjectDoesNotExist:
        messages.error(
            request,
            'Este Usuario no tiene un perfil creado'
        )
        data['form'] = AnuncioForm(instance=request.user)
        # return redirect('condominio:anuncios')


    return render(request, template_name, data)

@permission_required('condominio.delete_anuncio')
def borrarAnuncioViews(request, anuncio_id):

    data = {}
    template_name = 'condominio/eliminar_anuncio.html'

    data['anuncio'] = Anuncio.objects.get(id=anuncio_id)

    if data['anuncio'].perfil.user == request.user:
        if request.method == 'POST':
            data['anuncio'].delete()
            return redirect('condominio:anuncios')
    else:
        return HttpResponse('No estás autorizado para ver esta página.')


    return render(request, template_name, data)


from django.http import HttpResponse
# @check_profile
@permission_required('condominio.change_anuncio')
def editarAnuncioViews(request, anuncio_id):

    data = {}
    template_name = 'condominio/editar_anuncio.html'

    anuncio = Anuncio.objects.get(pk=anuncio_id)

    if anuncio.perfil.user == request.user:

condominio/templates/condominio/anuncios.html
{% extends "condominio/base.html" %}

{% block active_navbar_anuncios %}
<a class="nav-link active" href="{% url 'condominio:anuncios' %}">Anuncios</a>
{% endblock %}

{% block content_head %}
<div class="row mt-2">

  <div class="col-sm-6 col-md-8 col-lg-10">
    <h2>Anuncios Condominio</h2>
  </div>
  <div class="col-sm-6 col-md-4 col-lg-2">
    <a href="{% url 'condominio:crearAnun' %}" class="btn btn-success btn-block">Crear Anuncio</a>
  </div>

</div>
<hr>
{% endblock %}

{% block contenido %}
<div class="row">
  <div class="col">

    <section class="">

      <div class="row">
        <div class="col">
          <h3>Anuncios publicados por administradores.</h3>
        </div>
      </div>

      {% for anuncio in anunciosAdmin %}
      <div class="card shadow-sm rounded my-3 ">
        <div class="col my-1">

          <div class="row ">
            <div class="col">

              <div class="row">
                <div class="col-9">
                  <p class="" style="font-weight:bold; font-size:20px">{{anuncio.titulo}}</p>
                </div>
                {% if anuncio.perfil.user == request.user %}
                <div class="col-3">
                  {% if perms.condominio.change_anuncio %}
                  <a href="{% url 'condominio:editarAnun' anuncio.id %}">Editar
                    <i class="fas fa-edit color_update"></i>
                  </a>
                  {% endif %}
                  {% if perms.condominio.change_anuncio and perms.condominio.delete_anuncio %}
                  |
                  {% endif %}
                  {% if perms.condominio.delete_anuncio %}
                  <a href="{% url 'condominio:borrarAnun' anuncio.id %}">Eliminar
                    <i class="fas fa-trash-alt color_delete"></i>
                  </a>
                  {% endif %}
                </div>
                {% else %}
                
                <div class="col-3">

                </div>
                {% endif %}
              </div>
              <p class="">{{anuncio.descripcion}}</p>
              <p class="" style="font-style:oblique;">Publicado por:
              {{anuncio.perfil.user.first_name}}
              {{anuncio.perfil.user.last_name}}.
              {{anuncio.fecha}}
              </p>
              {% if anuncio.foto_anuncio %}
              <div class="media table-responsive">

                <img src="{{anuncio.foto_anuncio.url}}" alt="" style="height:400px;">
              </div>
              {% endif %}
            </div>
          </div>

        </div>

      </div>

      {% endfor %}


      <nav class="table-responsive">
        {% if anunciosAdmin.has_other_pages %}
          <ul class="pagination">
            {% if anunciosAdmin.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page={{ anunciosAdmin.previous_page_number }}">Anterior
                </a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <span class="page-link">Anterior</span>
              </li>
            {% endif %}
            {% for i in anunciosAdmin.paginator.page_range %}
              {% if anunciosAdmin.number == i %}
                <li class="page-item active">
                  <span class="page-link">{{ i }}
                    <span class="sr-only">(current)
                    </span>
                  </span>
                </li>
              {% else %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ i }}">{{ i }}
                  </a>
                </li>
              {% endif %}
            {% endfor %}
            {% if anunciosAdmin.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ anunciosAdmin.next_page_number }}">Siguiente
                </a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <span class="page-link">Siguiente
                </span>
              </li>
            {% endif %}
          </ul>
        {% endif %}
      </nav>
    </section>

    <hr>

    <section class="">

      <div class="row">
        <div class="col">
          <h3>Anuncios publicados por conserjes.</h3>
        </div>
      </div>

      {% for anuncio in anunciosConserje %}
      <div class="card shadow-sm rounded my-3 ">
        <div class="col my-1">

          <div class="row ">
            <div class="col">

              <div class="row">
                <div class="col-9">
                  <p class="" style="font-weight:bold; font-size:20px">{{anuncio.titulo}}</p>
                </div>
                {% if anuncio.perfil.user == request.user %}
                <div class="col-3">
                  {% if perms.condominio.change_anuncio %}
                  <a href="{% url 'condominio:editarAnun' anuncio.id %}">Editar
                    <i class="fas fa-edit color_update"></i>
                  </a>
                  {% endif %}
                  {% if perms.condominio.change_anuncio and perms.condominio.delete_anuncio %}
                  |
                  {% endif %}
                  {% if perms.condominio.delete_anuncio %}
                  <a href="{% url 'condominio:borrarAnun' anuncio.id %}">Eliminar
                    <i class="fas fa-trash-alt color_delete"></i>
                  </a>
                  {% endif %}
                </div>
                {% endif %}
              </div>
              <p class="">{{anuncio.descripcion}}</p>
              <p class="" style="font-style:oblique;">Publicado por:
              {{anuncio.perfil.user.first_name}}
              {{anuncio.perfil.user.last_name}}.
              {{anuncio.fecha}}
              </p>
              {% if anuncio.foto_anuncio %}
              <div class="media table-responsive">

                <img src="{{anuncio.foto_anuncio.url}}" alt="" style="height:400px;">
              </div>
              {% endif %}
            </div>
          </div>

        </div>

      </div>

      {% endfor %}


      <nav class="table-responsive">
        {% if anunciosConserje.has_other_pages %}
          <ul class="pagination">
            {% if anunciosConserje.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page2={{ anunciosConserje.previous_page_number }}">Anterior
                </a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <span class="page-link">Anterior</span>
              </li>
            {% endif %}
            {% for i in anunciosConserje.paginator.page_range %}
              {% if anunciosConserje.number == i %}
                <li class="page-item active">
                  <span class="page-link">{{ i }}
                    <span class="sr-only">(current)
                    </span>
                  </span>
                </li>
              {% else %}
                <li class="page-item">
                  <a class="page-link" href="?page2={{ i }}">{{ i }}
                  </a>
                </li>
              {% endif %}
            {% endfor %}
            {% if anunciosConserje.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page2={{ anunciosConserje.next_page_number }}">Siguiente
                </a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <span class="page-link">Siguiente
                </span>
              </li>
            {% endif %}
          </ul>
        {% endif %}
      </nav>
    </section>

    <hr>

    <section class="">

      <div class="row">
        <div class="col">
          <h3>Anuncios publicados por habitantes del condominio.</h3>
        </div>
      </div>

      {% for anuncio in anunciosUser %}
      <div class="card shadow-sm rounded my-3 ">
        <div class="col my-1">

          <div class="row ">
            <div class="col">

              <div class="row">
                <div class="col-9">
                  <p class="" style="font-weight:bold; font-size:20px">{{anuncio.titulo}}</p>
                </div>
                {% if anuncio.perfil.user == request.user %}
                <div class="col-3">
                  {% if perms.condominio.change_anuncio %}
                  <a href="{% url 'condominio:editarAnun' anuncio.id %}">Editar
                    <i class="fas fa-edit color_update"></i>
                  </a>
                  {% endif %}
                  {% if perms.condominio.change_anuncio and perms.condominio.delete_anuncio %}
                  |
                  {% endif %}
                  {% if perms.condominio.delete_anuncio %}
                  <a href="{% url 'condominio:borrarAnun' anuncio.id %}">Eliminar
                    <i class="fas fa-trash-alt color_delete"></i>
                  </a>
                  {% endif %}
                </div>
                {% endif %}
              </div>
              <p class="">{{anuncio.descripcion}}</p>
              <p class="" style="font-style:oblique;">Publicado por:
              {{anuncio.perfil.user.first_name}}
              {{anuncio.perfil.user.last_name}}.
              {{anuncio.fecha}}
              </p>
              {% if anuncio.foto_anuncio %}
              <div class="media table-responsive">

                <img src="{{anuncio.foto_anuncio.url}}" alt="" style="height:400px;">
              </div>
              {% endif %}
            </div>
          </div>

        </div>

      </div>

      {% endfor %}


      <nav class="table-responsive">
        {% if anunciosUser.has_other_pages %}
          <ul class="pagination">
            {% if anunciosUser.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page3={{ anunciosUser.previous_page_number }}">Anterior
                </a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <span class="page-link">Anterior</span>
              </li>
            {% endif %}
            {% for i in anunciosUser.paginator.page_range %}
              {% if anunciosUser.number == i %}
                <li class="page-item active">
                  <span class="page-link">{{ i }}
                    <span class="sr-only">(current)
                    </span>
                  </span>
                </li>
              {% else %}
                <li class="page-item">
                  <a class="page-link" href="?page3={{ i }}">{{ i }}
                  </a>
                </li>
              {% endif %}
            {% endfor %}
            {% if anunciosUser.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page3={{ anunciosUser.next_page_number }}">Siguiente
                </a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <span class="page-link">Siguiente
                </span>
              </li>
            {% endif %}
          </ul>
        {% endif %}
      </nav>
    </section>

  </div>
</div>
{% endblock %}

condominio/templates/condominio/usuarios.html
{% extends "condominio/base.html" %}

{% block active_navbar_opciones %}
<a class="nav-link active dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	Opciones
</a>
{% endblock %}

{% block content_head %}
<div class="row mt-2">

  <div class="col-sm-6 col-md-8 col-lg-10">
    <h2>Usuarios Condominio</h2>
  </div>
  <div class="col-sm-6 col-md-4 col-lg-2">
    {% if perms.condominio.add_perfil %}
    <a href="{% url 'auth_condominio:register' %}" class="btn btn-success btn-block">Crear Usuario</a>
    {% endif %}
  </div>

</div>
{% endblock %}

{% block contenido %}
<div class="row mt-4">
  <div class="col-md">
    <table class="table table-striped table-hover table-responsive">
      <thead class="">
        <tr>
          <th style="width:150px;">Usuario</th>
          <th style="width:250px;">Email</th>
          <th>Nombre/Apellido</th>
          <!-- <th>Tipo usuario</th> -->
          <th>Fecha creación</th>
          <th>Depto</th>
          {% if perms.condominio.change_perfil or perms.condominio.delete_perfil %}
          <th style="width:100px;">Acción</th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
        {% for perfil in perfiles %}
        <tr>
          <td>{{perfil.user.username}}</td>
          <td>{{perfil.user.email}}</td>
          <td>{{perfil.user.first_name}} {{perfil.user.last_name}}</td>
          <!-- <td>{{perfil.user.groups.all.0}}</td> -->
          <td>{{perfil.user.date_joined}}</td>
          <td>
            {% with perfil.depto_perfil.all as deptos %}
              {% if deptos %}
                {% for depto in deptos %}
                <span>{{depto.numero}}</span>
                {% endfor %}
              {% endif %}
            {% endwith %}
          </td>
          {% if perms.condominio.change_perfil or perms.condominio.delete_perfil %}
          <td>
            {% if perms.condominio.change_perfil %}
            <a href="{% url 'condominio:editarUser' perfil.id %}">Editar <i class="fas fa-edit color_update"></i></a>
            {% endif %}
            {% if perms.condominio.change_perfil and perms.condominio.delete_perfil %}
						|
            {% endif %}
            {% if perms.condominio.delete_perfil %}
            <a href="{% url 'condominio:borrarUser' perfil.user.id %}" style="text-decoration: none;">
							Eliminar
              <i class="fas fa-trash-alt color_delete"></i>
            </a>
            {% endif %}
          </td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <nav>
      {% if perfiles.has_other_pages %}
        <ul class="pagination">
          {% if perfiles.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ perfiles.previous_page_number }}">Anterior
              </a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <span class="page-link">Anterior</span>
            </li>
          {% endif %}
          {% for i in perfiles.paginator.page_range %}
            {% if perfiles.number == i %}
              <li class="page-item active">
                <span class="page-link">{{ i }}
                  <span class="sr-only">(current)
                  </span>
                </span>
              </li>
            {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}
                </a>
              </li>
            {% endif %}
          {% endfor %}
          {% if perfiles.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ perfiles.next_page_number }}">Siguiente
              </a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <span class="page-link">Siguiente
              </span>
            </li>
          {% endif %}
        </ul>
      {% endif %}
    </nav>

  </div>
</div>


{% endblock %}